print("========== Desasfio 02 ==========")
dia = input("Digite o dia de nascimento: " )
mes = input("Digite o Mês de nascimento: " )
ano = input("Digite o Ano de nascimento: " )
print("Você nasceu em", dia, mes, ano, ".", "Correto? ")
